### ISSUE TITLE
dodawanie do repozytorium gita

### ISSUE THREAD

**Issue by KrzysztofDolanski** [Javagda40z/Trener#2]
Hallo, Nie wiem co robię nie tak z dodawaniem projektu,
dodaję plik gitignore, doklejam do niego ze strony (https://github.com/github/gitignore/blob/master/Java.gitignore) wnętrze.

Dodaję z VCS git->remotes, 
comituję, zaznaczam odpowiednie pliki,
i po komendzie pusch wyskakuje mi "push rejected"

Zrobiłem od poczatku projekt (z tym że przekopiowałem każdą klasę) i również mam push rejected.

Pomocy,

**Comment by implssv** [comment]
Hallo! 
Generalnie to problem jest chyba taki, że wrzucasz właśnie z innego projektu, a tam pewnie zainicjalizowales repozytorium. To rozwiązanie zadziała z jednym projektem. To co możesz zrobić to stworzyć sobie nadrzędny folder i tam wrzucic oba projekty w osobnych folderach, a następnie spróbować wrzucić to wszystko(z folderu nadrzędnego) używając opcji force push. W Intelliju robisz to przez tę strzałkę na przycisku Push podczas pushowania projektu

**Comment by KrzysztofDolanski** [comment]
Super, dziękuję bardzo za podpowiedź. 
Faktycznie jeden projekt przyjmuje. Przekopiowałem klasy do nowego package w starym projekcie (który poprawnie wysyłał się do git-a) i działa.
